// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"time"
)

type Genre struct {
	GenreID   int64  `json:"genre_id"`
	GenreName string `json:"genre_name"`
}

type Movie struct {
	MovieID      int64          `json:"movie_id"`
	ImdbID       string         `json:"imdb_id"`
	Title        string         `json:"title"`
	PosterPath   string         `json:"poster_path"`
	YoutubeID    sql.NullString `json:"youtube_id"`
	AdminReview  sql.NullString `json:"admin_review"`
	RankingValue sql.NullInt32  `json:"ranking_value"`
	RankingName  sql.NullString `json:"ranking_name"`
}

type MovieGenre struct {
	MovieID int64 `json:"movie_id"`
	GenreID int64 `json:"genre_id"`
}

type User struct {
	UserID    int64     `json:"user_id"`
	PublicID  string    `json:"public_id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserFavGenre struct {
	UserID  int64 `json:"user_id"`
	GenreID int64 `json:"genre_id"`
}
