// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"
	"database/sql"
)

const createGenre = `-- name: CreateGenre :execresult
INSERT INTO genres(genre_name)
VALUES (?)
`

func (q *Queries) CreateGenre(ctx context.Context, genreName string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGenre, genreName)
}

const createMovie = `-- name: CreateMovie :execresult
INSERT INTO movies(imdb_id, title, poster_path)
VALUES(?, ?, ?)
`

type CreateMovieParams struct {
	ImdbID     string `json:"imdb_id"`
	Title      string `json:"title"`
	PosterPath string `json:"poster_path"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMovie, arg.ImdbID, arg.Title, arg.PosterPath)
}

const deleteGenre = `-- name: DeleteGenre :exec
DELETE FROM genres
WHERE genre_name = ?
`

func (q *Queries) DeleteGenre(ctx context.Context, genreName string) error {
	_, err := q.db.ExecContext(ctx, deleteGenre, genreName)
	return err
}

const getGenre = `-- name: GetGenre :one
SELECT genre_id, genre_name FROM genres
WHERE genre_name = ?
`

func (q *Queries) GetGenre(ctx context.Context, genreName string) (Genre, error) {
	row := q.db.QueryRowContext(ctx, getGenre, genreName)
	var i Genre
	err := row.Scan(&i.GenreID, &i.GenreName)
	return i, err
}

const getGenreByID = `-- name: GetGenreByID :one
SELECT genre_id, genre_name FROM genres
WHERE genre_id = ?
`

func (q *Queries) GetGenreByID(ctx context.Context, genreID int64) (Genre, error) {
	row := q.db.QueryRowContext(ctx, getGenreByID, genreID)
	var i Genre
	err := row.Scan(&i.GenreID, &i.GenreName)
	return i, err
}

const getMovie = `-- name: GetMovie :one
SELECT movie_id, imdb_id, title, poster_path, youtube_id, admin_review, ranking_value, ranking_name FROM movies
WHERE movie_id = ?
`

func (q *Queries) GetMovie(ctx context.Context, movieID int64) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovie, movieID)
	var i Movie
	err := row.Scan(
		&i.MovieID,
		&i.ImdbID,
		&i.Title,
		&i.PosterPath,
		&i.YoutubeID,
		&i.AdminReview,
		&i.RankingValue,
		&i.RankingName,
	)
	return i, err
}

const listGenres = `-- name: ListGenres :many
SELECT genre_id, genre_name FROM genres
ORDER BY genre_name
`

func (q *Queries) ListGenres(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.QueryContext(ctx, listGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.GenreID, &i.GenreName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovies = `-- name: ListMovies :many
SELECT movie_id, imdb_id, title, poster_path, youtube_id, admin_review, ranking_value, ranking_name FROM movies 
ORDER BY ranking_value
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.MovieID,
			&i.ImdbID,
			&i.Title,
			&i.PosterPath,
			&i.YoutubeID,
			&i.AdminReview,
			&i.RankingValue,
			&i.RankingName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGenre = `-- name: UpdateGenre :execresult
UPDATE genres
SET genre_name = ?
WHERE genre_id = ?
`

type UpdateGenreParams struct {
	GenreName string `json:"genre_name"`
	GenreID   int64  `json:"genre_id"`
}

func (q *Queries) UpdateGenre(ctx context.Context, arg UpdateGenreParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateGenre, arg.GenreName, arg.GenreID)
}
