-- +goose Up
CREATE TABLE IF NOT EXISTS users(
    user_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    public_id VARCHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
    username VARCHAR(20) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT NOW() NOT NULL,
    updated_at DATETIME DEFAULT NOW() NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS users;
